export const NATIVE_READER_TRANSPARENT_PORTRAIT_BACKGROUND = "transparent";
export const NATIVE_READER_TRANSPARENT_PORTRAIT_STYLE = {
  backgroundColor: NATIVE_READER_TRANSPARENT_PORTRAIT_BACKGROUND
} as const;
export const NATIVE_READER_CHARACTER_PORTRAIT_EMPTY_STYLE =
  NATIVE_READER_TRANSPARENT_PORTRAIT_STYLE;
export const NATIVE_READER_DRESS_PREVIEW_FALLBACK_BACKGROUND =
  "rgba(255, 255, 255, 0.04)";
export const NATIVE_READER_DRESS_PREVIEW_LOADING_OVERLAY_BACKGROUND =
  "rgba(0, 0, 0, 0.18)";
