export const NATIVE_READER_TRANSPARENT_PORTRAIT_BACKGROUND = "transparent";
export const NATIVE_READER_TRANSPARENT_PORTRAIT_STYLE = {
  backgroundColor: NATIVE_READER_TRANSPARENT_PORTRAIT_BACKGROUND
} as const;
